name: ci-dev

on:
  push:
    branches: [dev]

jobs:
  ci-dev:
    uses: Sneakertail/sneakertail-gitops/.github/workflows/service-ci.yaml@dev
    with:
      deploy_env: dev
      image_channel: dev
      charts_revision: dev
    secrets: inherit
