name: ci-dev

on:
  push:
    branches: [dev]

jobs:
  ci-dev:
    uses: Sneakertail/sneakertail-gitops/.github/workflows/service-ci-template.yaml@dev
    with:
      deploy_env: dev
      charts_revision: dev
      deploy_enabled: true
      image_tag: ${{ github.sha }}
    secrets: inherit
