name: ci-main

on:
  push:
    branches: [main]

jobs:
  ci-main:
    uses: Sneakertail/sneakertail-gitops/.github/workflows/service-ci-template.yaml@main
    permissions:
      contents: read
      packages: write
    with:
      deploy_env: prod
      charts_revision: main
      deploy_enabled: false
      image_tag: ${{ github.sha }}
    secrets: inherit
