name: ci-prod-manual

on:
  workflow_dispatch:

jobs:
  ci-prod:
    uses: Sneakertail/sneakertail-gitops/.github/workflows/service-ci.yaml@main
    with:
      deploy_env: prod
      image_channel: main
      charts_revision: main
    secrets: inherit
